### ISSUE TITLE
Future Security Architecture

### ISSUE THREAD

**Issue by georgwittberger** [T-Systems-MMS/skoop-server#30]
This issue is intended to discuss the future security architecture of the MySkills Server.

Recently, there was a discussion among the development team on which application level security should be enforced. Currently, the common approach is to annotate controller methods with `@PreAuthorize` to enforce security on the API level. The question is whether security should also be added to the service layer as the application grows. It is debatable whether there should be security annotations on both the controller and the service level.

## Variant "Controller-level Security"

In this approach we would enforce security only on the controller level. Developers will have to decide for each API endpoint which privileges are required to allow the call. For APIs which only provide data but do not alter the system state the only thing to decide is: Who should be able to view the data returned by the API call? For APIs altering the system state (e.g. executing procedures, writing data) it is more complicated because the API-based security must take into account all the changes to the system which may occur as a consequence of the API call. The controller method must be restricted to only allow calls from those users who are really privileged to perform all the operations which will happen as a result of the call.

Pros:

* Current approach, therefore almost no rework of existing implementation necessary.
* Privileges required for a certain API call are easy to read from the annotation on the controller method.

Cons:

* Tight coupling between security expression in the controller and security requirements of business logic located in downstream service beans.
* Higher potential for security vulnerabilities as the application grows and service beans are used by multiple controllers.

## Variant "Service-level Security"

In this approach we move all security annotations to the methods of service beans. Thus, services will only hand out data or allow operations to those users who are privileged to access the data or operations. The controllers will not have to worry about security at all. They simply call the required service methods and rely on their security model.

Pros:

* Access to certain parts of the domain model can be enforced in a central place - the service which is responsible for handling that domain.
* New APIs are automatically secured when they use existing services which enforce their security policy.

Cons:

* Harder to find out which privileges are really required to call a certain API endpoint. Can only be evaluated by traversing all involved service calls.
* May require introduction of DTOs which already hide some data aspects on the service level. For example, what if a partial scope of properties of a certain domain model should be visible to everyone but some confidential properties only to privileged users? Normally, the controller would simply decide which data to write into the API response. Now we would even need "views" on the internal service level.
* High effort to refactor all existing unit tests (moving security tests from controllers to services).

## Variant "Controller-level and Service-level Security"

In this approach we would try to adapt the best of both extremes. For example, security could be generally enforced on the controller level but for certain critical operations we could have additional security on the service level (e.g. for expensive operations, data changes, etc.).

**Comment by LebedkoDmitry** [comment]
**Variant "Service-level Security"**: 

> Harder to find out which privileges are really required to call a certain API endpoint. Can only be evaluated by traversing all involved service calls.

I would like to describe a scenario depicting details of implementation which should be discussed from my point of view. Let's take a look at the following scenario - there is a user with an abstract role named `FIRST_ROLE`. And the user wants to alter a domain object. The domain object is connected with several other domain objects which depend on it and must also be altered in the same transaction as the main object. And let's image the user has a permission to alter the main project but he does not have permissions to alter the connected objects. A service to perform the requested operation is likely to be implemented in a way the main object is altered first and only after that the connected objects are altered. When altering the connected objects the system realizes the user does not have permissions to do this and throws an exception rolling back performed changes.

From my point of view it would be much better if the system knows in advance if an entire operation can be completed successfully by a user. It would reduce time to response necessary to find out if a user can perform an operation. We should keep in mind that an entire operation to alter an object can be quite cost and time-consuming and operations performed before an exception was thrown can take a lot of CPU / RAM resources.

**Comment by georgwittberger** [comment]
Closing this discussion with the result: **We stick with controller-level authorization at the moment.**

Main reasons:

* It's easier to find out which privileges are required to perform a certain REST API call.
* It's easier to secure the whole operation and make sure that it can be executed consistently, avoiding any rollbacks of already changed data.
* It saves us from heavy refactoring of our current unit tests.
